Homework 3
Yulatun/React_6.12 pull request #2
Opened 2022-12-18 20:30 UTC by Yulatun

2022-12-19 04:37 UTC, pdalinchuk commented on src/components/cv/cv.css
> +
лишние строки в файле

2022-12-19 04:38 UTC, pdalinchuk commented on src/components/form/form.css
тоже лишняя строка

2022-12-19 04:39 UTC, pdalinchuk commented on src/components/textField/textField.css
> +
лишняя строка

2022-12-19 04:41 UTC, pdalinchuk commented on src/components/navigation/navigation.js
> +  ChangePage(data) {
методы (функции) начинаются с маленькой буквы

2022-12-19 04:43 UTC, pdalinchuk commented on src/components/cv/cv.js
> +    console.log(this.props.data);
лишний console.log

2022-12-19 04:47 UTC, pdalinchuk commented on src/components/form/form.js
> +    : 'поле «Сайт» должно начинаться с https:// ';
можно использовать value.startsWith('https://')

2022-12-19 04:53 UTC, pdalinchuk commented on src/components/form/form.js
> +        ></Input>
<Input></Input> => <Input />

2022-12-19 04:54 UTC, pdalinchuk commented on src/components/form/form.js
> +        <HelperText value={this.state.errors.name}></HelperText>
то же самое

2022-12-19 04:55 UTC, pdalinchuk commented on src/components/form/form.js
> +        <HelperText value={this.state.errors.lastName}></HelperText>
см. выше

2022-12-19 04:55 UTC, pdalinchuk commented on src/components/form/form.js
> +        <HelperText value={this.state.errors.date}></HelperText>
см. выше

2022-12-19 04:56 UTC, pdalinchuk commented on src/components/form/form.js
> +        <HelperText value={this.state.errors.tel}></HelperText>
см. выше

2022-12-19 04:56 UTC, pdalinchuk commented on src/components/form/form.js
> +        <HelperText value={this.state.errors.site}></HelperText>
см. выше

2022-12-19 05:12 UTC, pdalinchuk reviewed
Поправь моменты ниже, и у меня есть вопрос: у тебя учитываются пробелы в начале и в конце текста? И если да, то получается, эти лишние пробелы будут учитываться в счетчике символов?

2022-12-19 09:40 UTC, Yulatun commented on src/components/cv/cv.css
> +
done

2022-12-19 09:40 UTC, Yulatun commented on src/components/form/form.css
done

2022-12-19 09:40 UTC, Yulatun commented on src/components/textField/textField.css
> +
done

2022-12-19 09:40 UTC, Yulatun commented on src/components/navigation/navigation.js
> +  ChangePage(data) {
done

2022-12-19 09:40 UTC, Yulatun commented on src/components/cv/cv.js
> +    console.log(this.props.data);
done

2022-12-19 09:40 UTC, Yulatun commented on src/components/form/form.js
> +    : 'поле «Сайт» должно начинаться с https:// ';
done

2022-12-19 09:41 UTC, Yulatun commented on src/components/form/form.js
> +        ></Input>
done

2022-12-19 09:41 UTC, Yulatun commented on src/components/form/form.js
> +        <HelperText value={this.state.errors.name}></HelperText>
done

2022-12-19 09:41 UTC, Yulatun commented on src/components/form/form.js
> +        <HelperText value={this.state.errors.lastName}></HelperText>
done

2022-12-19 09:41 UTC, Yulatun commented on src/components/form/form.js
> +        <HelperText value={this.state.errors.date}></HelperText>
done

2022-12-19 09:41 UTC, Yulatun commented on src/components/form/form.js
> +        <HelperText value={this.state.errors.tel}></HelperText>
done

2022-12-19 09:41 UTC, Yulatun commented on src/components/form/form.js
> +        <HelperText value={this.state.errors.site}></HelperText>
done

2022-12-19 09:42 UTC, Yulatun commented
> 
Да, все верно у меня учитывались пробелы в начале и в конце текста. Исправила, добавив trim

2022-12-19 10:14 UTC, pdalinchuk requested changes
Проверить трим в textarea, т.к. нет возможности ввести более одного слова.

2022-12-19 11:34 UTC, pdalinchuk approved these changes

2022-12-20 19:27 UTC, poulkud approved these changes
Апрув

2022-12-21 20:47 UTC, merged